# Generated by Django 3.2.8 on 2021-10-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_rename_ubicación_hotel_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='nombre',
            new_name='nombreHotel',
        ),
    ]
