# Generated by Django 3.2.8 on 2021-10-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_rename_nombre_hotel_nombrehotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
    ]
